services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
          # - ./ws_location.conf:/etc/nginx/vhost.d/moodle.local:ro
        networks:
          - devbox
    moodle:
        # image: moodlehq/moodle-php-apache:$MOODLE_DOCKER_PHP_VERSION
        build:
          context: .
        volumes:
          - moodledata:/var/www/moodledata
          - $MOODLE_DOCKER_WWWROOT:/var/www/html
          - /Users/junxian/Desktop/FYP/spectrumGPT-tutoring-agent:/var/www/html/local/spectrumgpt
        depends_on:
          - postgres
        environment:
          - VIRTUAL_HOST=moodle.local
          # - CERT_NAME=localhost
        networks:
          - devbox
        command: >
          sh -c "php /var/www/html/local/spectrumgpt/cli/start_ws_server.php & apache2-foreground"
        ports:
          - "8091:8091"
    mail:
        image: axllent/mailpit:latest
        ports:
          - 8025:8025
        networks:
          - devbox
volumes:
    moodledata:
        external: true
networks:
  devbox:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
